#networks:
 # shared_net:
  #  external: true

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    tty: true
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
   # networks:
    #  - shared_net

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.16
    container_name: open-webui
    ports:
      - "3000:8080"
    restart: unless-stopped
    depends_on:
      - ollama
      - qdrant
     
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - VECTOR_DB=qdrant
      - ENABLE_QDRANT_MULTITENANCY_MODE=false
      - QDRANT_URI=http://qdrant:6333
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - NODE_OPTIONS=--max-old-space-size=2048
      - CONTENT_EXTRACTION_ENGINE=external
      - EXTERNAL_DOCUMENT_LOADER_URL=http://app-api:5000
      - EXTERNAL_DOCUMENT_LOADER_API_KEY=dummy
      #- TIKA_SERVER_URL=http://tika:9998
   # networks:
    #  - shared_net

  app-api:
    build: .
    ports:
      - "5001:5000"
    restart: unless-stopped
   # networks:
    #  - shared_net
    container_name: app-api

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "127.0.0.1:6333:6333"
    restart: unless-stopped
    volumes:
     - qdrant_storage:/qdrant/storage
   # networks:
    #  - shared_net
   
 # easyocr-api:
  #  build:
   #   context: .
    #container_name: easyocr-api   # ports:
    #  - "5001:5000"
   # restart: unless-stopped
   # depends_on:
    #  - tika
    #environment:
     # - TIKA_SERVER_URL=http://tika:9998

  tika-service:
    image: apache/tika:latest
   # container_name: tika-service
    ports:
      - "9998:9998"
    restart: unless-stopped
    #networks:
     # - shared_net

volumes:
  ollama:
  qdrant_storage:

